version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "portfoliodb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      my_network:
        ipv4_address: "172.18.0.2"

  web:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      my_network:
        ipv4_address: "172.18.0.3"

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"

volumes:
  db_data: