# Generated by Django 5.0.1 on 2024-01-28 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="title",
            new_name="discription",
        ),
    ]
