# Generated by Django 5.0.1 on 2024-01-28 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_rename_title_job_discription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="discription",
            new_name="description",
        ),
    ]
